In [2]:
import pandas as pd

In [3]:

df = pd.read_csv('C:/Users/What6/Documents/DataAnalysisDemo/globalRoadAccident/road_accident_dataset.csv') #dataFrame

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
0,USA,2002,October,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,2,58.625720,7412.752760,Wet,Weather,4,40499.856982,22072.878502,Europe,3866.273014
1,UK,2014,December,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,1,58.041380,4458.628820,Snow-covered,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224
2,USA,2012,July,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,4,42.374452,9856.915064,Wet,Speeding,4,29164.412982,58009.145124,South America,4408.889129
3,UK,2017,May,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,3,48.554014,4958.646267,Icy,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423
4,Canada,2002,July,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,4,18.318250,3843.191463,Icy,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

In [6]:
#access the columns

#df['Country']

df.Month

0          October
1         December
2             July
3              May
4             July
            ...
131995        June
131996     January
131997       March
131998         May
131999    November
Name: Month, Length: 132000, dtype: object

In [7]:
#access columns via index

#df['Country'][0]

df.Country[0]

'USA'

In [8]:
# df.info()
#df.head()
df.tail()

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

# Checking for missing values

In [9]:
# Count missing values in each column
#df.isnull().sum()

# Percentage of missing values per column
# (df.isnull().sum() / len(df)) * 100

# # Check if there are ANY missing values at all
df.isnull().values.any()

np.False_

# Checking for duplicates

In [10]:
# Count duplicate rows
# df.duplicated().sum()

# Display duplicate rows (if any)
df[df.duplicated()]

Empty DataFrame
Columns: [Country, Year, Month, Day of Week, Time of Day, Urban/Rural, Road Type, Weather Conditions, Visibility Level, Number of Vehicles Involved, Speed Limit, Driver Age Group, Driver Gender, Driver Alcohol Level, Driver Fatigue, Vehicle Condition, Pedestrians Involved, Cyclists Involved, Accident Severity, Number of Injuries, Number of Fatalities, Emergency Response Time, Traffic Volume, Road Condition, Accident Cause, Insurance Claims, Medical Cost, Economic Loss, Region, Population Density]
Index: []

[0 rows x 30 columns]

In [11]:
# Handling missing values if find any 

# Drop rows with missing values
df.dropna(inplace=True)

# Fill missing values with mean (for numeric columns)
df['Traffic Volume'] = df['Traffic Volume'].fillna(df['Traffic Volume'].mean())

# Fill missing values with mode (for categorical columns)
df['Accident Cause'] = df['Accident Cause'].fillna(df['Accident Cause'].mode()[0])

In [12]:
# Handling duplicates data if find any

# Remove duplicate rows
df.drop_duplicates(inplace=True)

conclusion there was none duplicates and none missing values after my research in this global data

# Convert DateTime columns into proper formats.

In [13]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
0,USA,2002,October,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,2,58.625720,7412.752760,Wet,Weather,4,40499.856982,22072.878502,Europe,3866.273014
1,UK,2014,December,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,1,58.041380,4458.628820,Snow-covered,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224
2,USA,2012,July,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,4,42.374452,9856.915064,Wet,Speeding,4,29164.412982,58009.145124,South America,4408.889129
3,UK,2017,May,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,3,48.554014,4958.646267,Icy,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423
4,Canada,2002,July,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,4,18.318250,3843.191463,Icy,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

In [14]:
# First, ensure Month names are converted to proper numbers
df['Month'] = pd.to_datetime(df['Month'], format='%B').dt.month  # e.g., "October" → 10

# Create a base date using Year + Month
df['Date'] = pd.to_datetime(df[['Year', 'Month']].assign(Day=1))

# # Map Day of Week to numbers (Monday=0, Sunday=6)
# day_map = {
#     "Monday": 0, "Tuesday": 1, "Wednesday": 2, "Thursday": 3,
#     "Friday": 4, "Saturday": 5, "Sunday": 6
# }
# df['Day of Week Num'] = df['Day of Week'].map(day_map)

# Map Time of Day to rough hour slots (customize if needed)
time_map = {
    "Morning": 9,       # around 9 AM
    "Afternoon": 15,    # around 3 PM
    "Evening": 19,      # around 7 PM
    "Night": 23         # around 11 PM
}
df['Hour'] = df['Time of Day'].map(time_map)

# Now build a proper datetime
df['Datetime'] = pd.to_datetime(
    df[['Year', 'Month']].assign(Day=1)
) + pd.to_timedelta(df['Hour'], unit='h')

# Drop helper columns if not needed
# df.drop(columns=['Day of Week Num', 'Hour'], inplace=True)

In [15]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Hour,Datetime
0,USA,2002,10,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,Wet,Weather,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,19,2002-10-01 19:00:00
1,UK,2014,12,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,Snow-covered,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,19,2014-12-01 19:00:00
2,USA,2012,7,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,Wet,Speeding,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,15,2012-07-01 15:00:00
3,UK,2017,5,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,Icy,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,19,2017-05-01 19:00:00
4,Canada,2002,7,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,Icy,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,15,2002-07-01 15:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,19,2023-06-01 19:00:00
131996,Brazil,2023,1,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,9,2023-01-01 09:00:00
131997,Russia,2021,3,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,15,2021-03-01 15:00:00
131998,Australia,2002,5,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,9,2002-05-01 09:00:00
131999,USA,2022,11,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,9,2022-11-01 09:00:00

# Create new features like "Hour"
,
"Weekday
"
, or "Month" from timestamp.

In [16]:
# Ensure 'Datetime' is in datetime format
df['Datetime'] = pd.to_datetime(df['Datetime'])

df = df.drop(columns=["Day of Week"])
# Create new features from timestamp
#df['Hour'] = df['Datetime'].dt.hour                # Extract hour (0–23)
df['Weekday'] = df['Datetime'].dt.dayofweek + 1    # Monday=1, Sunday=7
#df['Month'] = df['Datetime'].dt.month              # 1=January, 12=December

In [17]:
df

,Country,Year,Month,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,Speed Limit,...,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Hour,Datetime,Weekday
0,USA,2002,10,Evening,Rural,Street,Windy,220.414651,1,37,...,Weather,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,19,2002-10-01 19:00:00,2
1,UK,2014,12,Evening,Urban,Street,Windy,168.311358,3,96,...,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,19,2014-12-01 19:00:00,1
2,USA,2012,7,Afternoon,Urban,Highway,Snowy,341.286506,4,62,...,Speeding,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,15,2012-07-01 15:00:00,7
3,UK,2017,5,Evening,Urban,Main Road,Clear,489.384536,2,78,...,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,19,2017-05-01 19:00:00,1
4,Canada,2002,7,Afternoon,Rural,Highway,Rainy,348.344850,1,98,...,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,15,2002-07-01 15:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Evening,Rural,Main Road,Foggy,351.740871,4,95,...,Speeding,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,19,2023-06-01 19:00:00,4
131996,Brazil,2023,1,Morning,Rural,Main Road,Foggy,95.563567,1,100,...,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,9,2023-01-01 09:00:00,7
131997,Russia,2021,3,Afternoon,Urban,Street,Clear,74.112102,3,36,...,Speeding,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,15,2021-03-01 15:00:00,1
131998,Australia,2002,5,Morning,Urban,Street,Rainy,276.612565,3,99,...,Speeding,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,9,2002-05-01 09:00:00,3
131999,USA,2022,11,Morning,Urban,Street,Windy,253.531380,3,44,...,Speeding,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,9,2022-11-01 09:00:00,2

In [18]:
#dropped day of week Num column
# df = df.drop(columns=['Day of Week Num'])

In [19]:
df

,Country,Year,Month,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,Speed Limit,...,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Hour,Datetime,Weekday
0,USA,2002,10,Evening,Rural,Street,Windy,220.414651,1,37,...,Weather,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,19,2002-10-01 19:00:00,2
1,UK,2014,12,Evening,Urban,Street,Windy,168.311358,3,96,...,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,19,2014-12-01 19:00:00,1
2,USA,2012,7,Afternoon,Urban,Highway,Snowy,341.286506,4,62,...,Speeding,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,15,2012-07-01 15:00:00,7
3,UK,2017,5,Evening,Urban,Main Road,Clear,489.384536,2,78,...,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,19,2017-05-01 19:00:00,1
4,Canada,2002,7,Afternoon,Rural,Highway,Rainy,348.344850,1,98,...,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,15,2002-07-01 15:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Evening,Rural,Main Road,Foggy,351.740871,4,95,...,Speeding,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,19,2023-06-01 19:00:00,4
131996,Brazil,2023,1,Morning,Rural,Main Road,Foggy,95.563567,1,100,...,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,9,2023-01-01 09:00:00,7
131997,Russia,2021,3,Afternoon,Urban,Street,Clear,74.112102,3,36,...,Speeding,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,15,2021-03-01 15:00:00,1
131998,Australia,2002,5,Morning,Urban,Street,Rainy,276.612565,3,99,...,Speeding,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,9,2002-05-01 09:00:00,3
131999,USA,2022,11,Morning,Urban,Street,Windy,253.531380,3,44,...,Speeding,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,9,2022-11-01 09:00:00,2

# Encode categorical variables if needed.Handle outliers and duplicate entries.

In [28]:
import pandas as pd

#one hot encode which create dummies columns or extra columns 
#of unique values from original column ie country column is given then 
#one hot encode will create dummies columns as countryfrance countryusa countryindia
#and each values are converted into binary that is either 0 or 1. 0 for value notexists
#1 for values exists in original column and each represented separately in each columns that is
#countryusa countryfrance countryindia

# List of categorical columns to be one-hot encoded
label_cols = [
    'Country', 'Region', 'Weekday', 'Time of Day',
    'Urban/Rural', 'Road Type', 'Weather Conditions',
    'Road Condition', 'Accident Cause'
]

# One-Hot Encode categorical variables
df_encoded = pd.get_dummies(df, columns=label_cols, drop_first=True)

#drop first = true means if the values are 0 on both side then it will 1 on first column that is france in this ex case 
#which will remove redundant values or column

# Display the first few rows of the encoded DataFrame
df_encoded.head()

#hotspot accident area feature proposed by sri shanya.

,Year,Month,Visibility Level,Number of Vehicles Involved,Speed Limit,Driver Age Group,Driver Gender,Driver Alcohol Level,Driver Fatigue,Vehicle Condition,...,Weather Conditions_Rainy,Weather Conditions_Snowy,Weather Conditions_Windy,Road Condition_Icy,Road Condition_Snow-covered,Road Condition_Wet,Accident Cause_Drunk Driving,Accident Cause_Mechanical Failure,Accident Cause_Speeding,Accident Cause_Weather
0,2002,10,220.414651,1,37,18-25,Male,0.051921,0,Poor,...,False,False,True,False,False,True,False,False,False,True
1,2014,12,168.311358,3,96,18-25,Female,0.234893,1,Poor,...,False,False,True,False,True,False,False,True,False,False
2,2012,7,341.286506,4,62,41-60,Male,0.142366,0,Moderate,...,False,True,False,False,False,True,False,False,True,False
3,2017,5,489.384536,2,78,18-25,Male,0.120815,1,Good,...,False,False,False,True,False,False,False,False,False,False
4,2002,7,348.344850,1,98,41-60,Male,0.155842,1,Poor,...,True,False,False,True,False,False,False,False,False,False

In [21]:
#2 handling outliers
import numpy as np

num_cols = ['Visibility Level', 'Traffic Volume', 'Medical Cost', 'Economic Loss']

for col in num_cols:
    z_scores = (df[col] - df[col].mean()) / df[col].std()
    df = df[np.abs(z_scores) < 3]  # Keep only values within 3 std

In [22]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [23]:
# # Count duplicates
# print("Duplicate rows:", df.duplicated().sum())

# # Drop duplicates
# df = df.drop_duplicates()

#there is no duplicate so this line didnot needed

# lasso technique for outlier helpful 
predict accident zone areas

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132000 entries, 0 to 131999
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Country                      132000 non-null  object
 1   Year                         132000 non-null  int64
 2   Month                        132000 non-null  int32
 3   Time of Day                  132000 non-null  object
 4   Urban/Rural                  132000 non-null  object
 5   Road Type                    132000 non-null  object
 6   Weather Conditions           132000 non-null  object
 7   Visibility Level             132000 non-null  float64
 8   Number of Vehicles Involved  132000 non-null  int64
 9   Speed Limit                  132000 non-null  int64
 10  Driver Age Group             132000 non-null  object
 11  Driver Gender                132000 non-null  object
 12  Driver Alcohol Level         132000 non-null  float64
 13  Driver Fatigue               132000 non-null  int64
 14  Vehicle Condition            132000 non-null  object
 15  Pedestrians Involved         132000 non-null  int64
 16  Cyclists Involved            132000 non-null  int64
 17  Accident Severity            132000 non-null  object
 18  Number of Injuries           132000 non-null  int64
 19  Number of Fatalities         132000 non-null  int64
 20  Emergency Response Time      132000 non-null  float64
 21  Traffic Volume               132000 non-null  float64
 22  Road Condition               132000 non-null  object
 23  Accident Cause               132000 non-null  object
 24  Insurance Claims             132000 non-null  int64
 25  Medical Cost                 132000 non-null  float64
 26  Economic Loss                132000 non-null  float64
 27  Region                       132000 non-null  object
 28  Population Density           132000 non-null  float64
 29  Date                         132000 non-null  datetime64[ns]
 30  Hour                         132000 non-null  int64
 31  Datetime                     132000 non-null  datetime64[ns]
 32  Weekday                      132000 non-null  int32
dtypes: datetime64[ns](2), float64(7), int32(2), int64(10), object(12)
memory usage: 32.2+ MB