In [43]:
import pandas as pd

In [44]:

df = pd.read_csv('C:/Users/What6/Documents/DataAnalysisDemo/globalRoadAccident/road_accident_dataset.csv') #dataFrame

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
0,USA,2002,October,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,2,58.625720,7412.752760,Wet,Weather,4,40499.856982,22072.878502,Europe,3866.273014
1,UK,2014,December,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,1,58.041380,4458.628820,Snow-covered,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224
2,USA,2012,July,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,4,42.374452,9856.915064,Wet,Speeding,4,29164.412982,58009.145124,South America,4408.889129
3,UK,2017,May,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,3,48.554014,4958.646267,Icy,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423
4,Canada,2002,July,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,4,18.318250,3843.191463,Icy,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

In [47]:
#access the columns

#df['Country']

df.Month

0          October
1         December
2             July
3              May
4             July
            ...
131995        June
131996     January
131997       March
131998         May
131999    November
Name: Month, Length: 132000, dtype: object

In [48]:
#access columns via index

#df['Country'][0]

df.Country[0]

'USA'

In [49]:
# df.info()
#df.head()
df.tail()

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

# Checking for missing values

In [50]:
# Count missing values in each column
#df.isnull().sum()

# Percentage of missing values per column
# (df.isnull().sum() / len(df)) * 100

# # Check if there are ANY missing values at all
df.isnull().values.any()

np.False_

# Checking for duplicates

In [51]:
# Count duplicate rows
# df.duplicated().sum()

# Display duplicate rows (if any)
df[df.duplicated()]

Empty DataFrame
Columns: [Country, Year, Month, Day of Week, Time of Day, Urban/Rural, Road Type, Weather Conditions, Visibility Level, Number of Vehicles Involved, Speed Limit, Driver Age Group, Driver Gender, Driver Alcohol Level, Driver Fatigue, Vehicle Condition, Pedestrians Involved, Cyclists Involved, Accident Severity, Number of Injuries, Number of Fatalities, Emergency Response Time, Traffic Volume, Road Condition, Accident Cause, Insurance Claims, Medical Cost, Economic Loss, Region, Population Density]
Index: []

[0 rows x 30 columns]

In [52]:
# Handling missing values if find any 

# Drop rows with missing values
df.dropna(inplace=True)

# Fill missing values with mean (for numeric columns)
df['Traffic Volume'] = df['Traffic Volume'].fillna(df['Traffic Volume'].mean())

# Fill missing values with mode (for categorical columns)
df['Accident Cause'] = df['Accident Cause'].fillna(df['Accident Cause'].mode()[0])

In [53]:
# Handling duplicates data if find any

# Remove duplicate rows
df.drop_duplicates(inplace=True)

conclusion there was none duplicates and none missing values after my research in this global data

# Convert DateTime columns into proper formats.

In [54]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Number of Fatalities,Emergency Response Time,Traffic Volume,Road Condition,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density
0,USA,2002,October,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,2,58.625720,7412.752760,Wet,Weather,4,40499.856982,22072.878502,Europe,3866.273014
1,UK,2014,December,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,1,58.041380,4458.628820,Snow-covered,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224
2,USA,2012,July,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,4,42.374452,9856.915064,Wet,Speeding,4,29164.412982,58009.145124,South America,4408.889129
3,UK,2017,May,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,3,48.554014,4958.646267,Icy,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423
4,Canada,2002,July,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,4,18.318250,3843.191463,Icy,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,June,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,0,37.405598,1907.208566,Icy,Speeding,3,18640.125887,50695.311876,Asia,173.307333
131996,Brazil,2023,January,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,4,17.054490,2706.253339,Dry,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810
131997,Russia,2021,March,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,3,55.558876,6860.161645,Dry,Speeding,9,24696.058692,8132.133502,Asia,4196.244517
131998,Australia,2002,May,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,2,19.100498,1523.299088,Wet,Speeding,8,13486.716680,17607.573072,Europe,2911.904030
131999,USA,2022,November,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,4,28.037108,7662.853082,Snow-covered,Speeding,6,3240.358544,27765.168982,Asia,2949.568694

In [55]:
# First, ensure Month names are converted to proper numbers
df['Month'] = pd.to_datetime(df['Month'], format='%B').dt.month  # e.g., "October" → 10

# Create a base date using Year + Month
df['Date'] = pd.to_datetime(df[['Year', 'Month']].assign(Day=1))

# Map Day of Week to numbers (Monday=0, Sunday=6)
day_map = {
    "Monday": 0, "Tuesday": 1, "Wednesday": 2, "Thursday": 3,
    "Friday": 4, "Saturday": 5, "Sunday": 6
}
df['Day of Week Num'] = df['Day of Week'].map(day_map)

# Map Time of Day to rough hour slots (customize if needed)
time_map = {
    "Morning": 9,       # around 9 AM
    "Afternoon": 15,    # around 3 PM
    "Evening": 19,      # around 7 PM
    "Night": 23         # around 11 PM
}
df['Hour'] = df['Time of Day'].map(time_map)

# Now build a proper datetime
df['Datetime'] = pd.to_datetime(
    df[['Year', 'Month']].assign(Day=1)
) + pd.to_timedelta(df['Hour'], unit='h')

# Drop helper columns if not needed
# df.drop(columns=['Day of Week Num', 'Hour'], inplace=True)

In [56]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Day of Week Num,Hour,Datetime
0,USA,2002,10,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,Weather,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,1,19,2002-10-01 19:00:00
1,UK,2014,12,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,5,19,2014-12-01 19:00:00
2,USA,2012,7,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,Speeding,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,6,15,2012-07-01 15:00:00
3,UK,2017,5,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,5,19,2017-05-01 19:00:00
4,Canada,2002,7,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,1,15,2002-07-01 15:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,Speeding,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,2,19,2023-06-01 19:00:00
131996,Brazil,2023,1,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,1,9,2023-01-01 09:00:00
131997,Russia,2021,3,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,Speeding,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,2,15,2021-03-01 15:00:00
131998,Australia,2002,5,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,Speeding,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,1,9,2002-05-01 09:00:00
131999,USA,2022,11,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,Speeding,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,1,9,2022-11-01 09:00:00

# Create new features like "Hour"
,
"Weekday
"
, or "Month" from timestamp.

In [57]:
# Ensure 'Datetime' is in datetime format
df['Datetime'] = pd.to_datetime(df['Datetime'])

# Create new features from timestamp
df['Hour'] = df['Datetime'].dt.hour                # Extract hour (0–23)
df['Weekday'] = df['Datetime'].dt.dayofweek + 1    # Monday=1, Sunday=7
df['Month'] = df['Datetime'].dt.month              # 1=January, 12=December

In [58]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Day of Week Num,Hour,Datetime,Weekday
0,USA,2002,10,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,1,19,2002-10-01 19:00:00,2
1,UK,2014,12,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,5,19,2014-12-01 19:00:00,1
2,USA,2012,7,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,6,15,2012-07-01 15:00:00,7
3,UK,2017,5,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,5,19,2017-05-01 19:00:00,1
4,Canada,2002,7,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,1,15,2002-07-01 15:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,2,19,2023-06-01 19:00:00,4
131996,Brazil,2023,1,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,1,9,2023-01-01 09:00:00,7
131997,Russia,2021,3,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,2,15,2021-03-01 15:00:00,1
131998,Australia,2002,5,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,1,9,2002-05-01 09:00:00,3
131999,USA,2022,11,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,1,9,2022-11-01 09:00:00,2

In [59]:
df = df.drop(columns=['Day of Week Num'])

In [60]:
df

,Country,Year,Month,Day of Week,Time of Day,Urban/Rural,Road Type,Weather Conditions,Visibility Level,Number of Vehicles Involved,...,Accident Cause,Insurance Claims,Medical Cost,Economic Loss,Region,Population Density,Date,Hour,Datetime,Weekday
0,USA,2002,10,Tuesday,Evening,Rural,Street,Windy,220.414651,1,...,Weather,4,40499.856982,22072.878502,Europe,3866.273014,2002-10-01,19,2002-10-01 19:00:00,2
1,UK,2014,12,Saturday,Evening,Urban,Street,Windy,168.311358,3,...,Mechanical Failure,3,6486.600073,9534.399441,North America,2333.916224,2014-12-01,19,2014-12-01 19:00:00,1
2,USA,2012,7,Sunday,Afternoon,Urban,Highway,Snowy,341.286506,4,...,Speeding,4,29164.412982,58009.145124,South America,4408.889129,2012-07-01,15,2012-07-01 15:00:00,7
3,UK,2017,5,Saturday,Evening,Urban,Main Road,Clear,489.384536,2,...,Distracted Driving,3,25797.212566,20907.151302,Australia,2810.822423,2017-05-01,19,2017-05-01 19:00:00,1
4,Canada,2002,7,Tuesday,Afternoon,Rural,Highway,Rainy,348.344850,1,...,Distracted Driving,8,15605.293921,13584.060759,South America,3883.645634,2002-07-01,15,2002-07-01 15:00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131995,Germany,2023,6,Wednesday,Evening,Rural,Main Road,Foggy,351.740871,4,...,Speeding,3,18640.125887,50695.311876,Asia,173.307333,2023-06-01,19,2023-06-01 19:00:00,4
131996,Brazil,2023,1,Tuesday,Morning,Rural,Main Road,Foggy,95.563567,1,...,Drunk Driving,2,48161.129965,20260.167191,Asia,4375.443810,2023-01-01,9,2023-01-01 09:00:00,7
131997,Russia,2021,3,Wednesday,Afternoon,Urban,Street,Clear,74.112102,3,...,Speeding,9,24696.058692,8132.133502,Asia,4196.244517,2021-03-01,15,2021-03-01 15:00:00,1
131998,Australia,2002,5,Tuesday,Morning,Urban,Street,Rainy,276.612565,3,...,Speeding,8,13486.716680,17607.573072,Europe,2911.904030,2002-05-01,9,2002-05-01 09:00:00,3
131999,USA,2022,11,Tuesday,Morning,Urban,Street,Windy,253.531380,3,...,Speeding,6,3240.358544,27765.168982,Asia,2949.568694,2022-11-01,9,2022-11-01 09:00:00,2

# Encode categorical variables if needed.Handle outliers and duplicate entries.

In [61]:
# 1 categorical variables
from sklearn.preprocessing import LabelEncoder

label_cols = ['Country', 'Region', 'Day of Week', 'Time of Day',
              'Urban/Rural', 'Road Type', 'Weather Conditions',
              'Road Condition', 'Accident Cause']

le = LabelEncoder()
for col in label_cols:
    df[col] = le.fit_transform(df[col])

In [62]:
df = pd.get_dummies(df, columns=label_cols, drop_first=True)

In [67]:
#2 handling outliers
import numpy as np

num_cols = ['Visibility Level', 'Traffic Volume', 'Medical Cost', 'Economic Loss']

for col in num_cols:
    z_scores = (df[col] - df[col].mean()) / df[col].std()
    df = df[np.abs(z_scores) < 3]  # Keep only values within 3 std

In [66]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [68]:
# # Count duplicates
# print("Duplicate rows:", df.duplicated().sum())

# # Drop duplicates
# df = df.drop_duplicates()

#there is no duplicate so this line didnot needed